Sigint 896 specific bridge download and caching
synopsys-sig/synopsys-security-scan-plugin pull request #17
Opened 2023-07-05 11:30 UTC by jahid1209

- Added caching by parsing DOM so that development can move forward (will change the strategy after api endpoint is available.)

- Added functionality to download bridge from the url and version provided by the user.

- Added functionality to install bridge in the default location( Kishori's suggestion). If user provides the installation location, then bridge will be installed in the specified location.

- Added bridge parameter validation

- Addressed all of Kishori's review comment except this.

1. > If we download the zip to temp directory, we may not need to call delete.

This wasn't addressed because jvm doesn't erase the temp file even after the termination. Therefore, we need to call `delete` explicitly.

2023-07-05 19:34 UTC, zaman-akib requested changes

2023-07-05 19:34 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/global/Utility.java
> +        File file = new File(bridgeInstallationPath, BridgeParams.BLACKDUCK_JSON_FILE_NAME);
Have to keep in mind that later we may need to delete coverity and polaris json file as well

2023-07-05 19:34 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/service/BlackDuckParametersService.java
Here we noticed a bug, if the global configuration is not done then `config.getBlackDuckUrl()` and `config.getBlackDuckCredentialsId()` produce null pointer exception. So we need to handle this. We may return the empty map if these values are empty or null.

2023-07-05 19:34 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/SecurityScanner.java
> +//            BridgeDownloaderAndExecutor bridgeDownloaderAndExecutor = new BridgeDownloaderAndExecutor(listener, envVars);
can be removed

2023-07-05 19:34 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/global/Utility.java
> +    public static void copyRepository(String targetDirectory, String pluginWorkspaceDirectory) {
We can alter the parameters place. 
`copyRepository(pluginWorkspaceDirectory, targetDirectory)` is easily understandable like `FileUtils.copyDirectory(workspaceDirectory, targetDir)`

2023-07-05 19:34 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/bridge/BridgeDownloadManager.java
> +    private final String versionFile = "versions.txt";
should put a newline here

2023-07-06 02:36 UTC, jahid1209 commented
Thanks @zaman-akib for the feedback!

2023-07-06 02:37 UTC, merged