SIGINT-1073: add support for multiple scan types
synopsys-sig/synopsys-security-scan-plugin pull request #52
Opened 2023-08-31 12:49 UTC by zaman-akib

- removed strategy pattern for parameters as these are not needed for multiple scan type support
- added support for multiple scan types
- added unit tests for `ScanParametersService`

2023-09-01 09:51 UTC, jahid1209 requested changes

2023-09-01 09:51 UTC, jahid1209 commented on src/main/java/com/synopsys/integration/jenkins/scan/global/ApplicationConstants.java
> +
More clean variable name would be `BLACKDUCK_INPUT_JSON_PREFIX ` and so on.

2023-09-01 09:51 UTC, jahid1209 commented on src/main/java/com/synopsys/integration/jenkins/scan/service/ScannerArgumentService.java
> +        }
The entire if segment could in a separate method named: `prepareScanTypeSpecificCommands(....)`

2023-09-04 07:20 UTC, jahid1209 approved these changes

2023-09-04 12:24 UTC, kishorikumar requested changes

2023-09-04 12:42 UTC, kishorikumar approved these changes

2023-09-04 12:50 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/ScanPipelineCommands.java
> +        if (!scanParameters.containsKey(ApplicationConstants.SCAN_TYPE_KEY)) {
As discussed with @sig-tithi , if no scan_type is selected or passed either in global configuration or jenkins pipeline parameter, plugin will error out. 

If later there is any changes, we can update here.

2023-09-04 12:51 UTC, merged