SIGINT-1111: Jenkins Plugin: Map platform specific bridge download URL from UI to code
synopsys-sig/synopsys-security-scan-plugin pull request #63
Opened 2023-09-12 09:53 UTC by maksudur-rahman-maruf

-  Mapped platform specific bridge download URL from UI to code

2023-09-12 12:48 UTC, jahid1209 approved these changes

2023-09-12 12:55 UTC, zaman-akib requested changes

2023-09-12 12:55 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/extension/global/ScannerGlobalConfig.java
> +    private String synopsysBridgeDownloadUrlForMac;
add `HelpMarkdown`

2023-09-12 12:55 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/extension/global/ScannerGlobalConfig.java
> +    private String synopsysBridgeDownloadUrlForWindows;
add `HelpMarkdown`

2023-09-12 12:55 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/extension/global/ScannerGlobalConfig.java
> +    private String synopsysBridgeDownloadUrlForLinux;
add `HelpMarkdown`

2023-09-12 12:55 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/service/ScanCommandsFactory.java
> +        else return synopsysBridgeDownloadUrlForWindows;
add curly braces.

format these as- 

```
if () {
} else if () {
}
```

2023-09-13 07:49 UTC, jahid1209 approved these changes

2023-09-13 07:49 UTC, jahid1209 commented on src/main/java/com/synopsys/integration/jenkins/scan/extension/global/ScannerGlobalConfig.java
Remove this blank line.

2023-09-13 08:31 UTC, zaman-akib approved these changes

2023-09-13 08:32 UTC, merged

2023-09-13 08:57 UTC, kishorikumar approved these changes