No stacktrace for known errors generated by synopsys-bridge
synopsys-sig/synopsys-security-scan-plugin pull request #67
Opened 2023-09-14 09:13 UTC by jahid1209

- Added new print stacktrace logic 

- Added unit test for `getSynopsysSecurityPlatforms` method

- Removed jsoup dependency from build.gradle

2023-09-14 09:15 UTC, jahid1209 commented on src/main/java/com/synopsys/integration/jenkins/scan/global/ExceptionMessages.java
> +
@kishorikumar and @sig-tithi 
These are the error messages for the known exceptions. Please check if these are the messages we want to show.

2023-09-14 10:28 UTC, maksudur-rahman-maruf approved these changes

2023-09-14 10:52 UTC, zaman-akib requested changes

2023-09-14 10:52 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/ScanPipelineCommands.java
> +                throw new NoStackTraceException(exitCodeToMessage.get(exitCode));
Need to check if we can use the **`Run`** object here from `createPipelineCommand` method to set current build as failed or aborted.

```
run.getPreviousBuild().setResult(Result.FAILURE);
run.getNextBuild().setResult(Result.FAILURE);
```

We need to check which method (`getPreviousBuild()` or `getNextBuild()`) get the current build.

Also need to check whether we need to use `Result.FAILURE` or `Result.ABORT`

2023-09-14 11:05 UTC, zaman-akib commented on src/main/java/com/synopsys/integration/jenkins/scan/exception/NoStackTraceException.java
> +public class NoStackTraceException extends Exception {
_`com.synopsys.integration.jenkins.scan.exception.NoStackTraceException: Workflow failed! Exit Code: 2 Error from adapter`_

If we go with this Exception way (not jenkins build failure way), then maybe we need to rename this `NoStackTraceException` class name. This name doesn't suit in client side.

2023-09-18 08:51 UTC, zaman-akib approved these changes

2023-09-18 10:56 UTC, merged